module.exports =
[
    {ticker: "KCS", low: 0.4, high: 0.4},
    {ticker: "RPX", low: 0.4, high: 0.4},
    {ticker: "QLC", low: 0.4, high: 0.4},
    {ticker: "XRB", low: 0.4, high: 0.4},
    {ticker: "AIX", low: 0.4, high: 0.4},
    {ticker: "DBC", low: 0.3, high: 0.45},
    {ticker: "DENT", low: 0.4, high: 0.4},
    {ticker: "SNOV", low: 0.4, high: 0.3},
    {ticker: "CAN", low: 0.4, high: 0.4},
    {ticker: "UTK", low: 0.4, high: 0.4},
    {ticker: "POE", low: 0.4, high: 0.4},
    {ticker: "PRL", low: 0.4, high: 0.4},
    {ticker: "TFL", low: 0.4, high: 0.4},
    {ticker: "XLR", low: 0.4, high: 0.4},
    {ticker: "BNTY", low: 0.4, high: 0.4},
    {ticker: "DRGN", low: 0.4, high: 0.3},
    {ticker: "LEND", low: 0.4, high: 0.4},
    {ticker: "LA", low: 0.4, high: 0.4},
    {ticker: "CAG", low: 0.4, high: 0.4},
    {ticker: "AION", low: 0.4, high: 0.4},
    {ticker: "ONION", low: 0.4, high: 0.4},

    {ticker: "REQ", low: 0.4, high: 0.4},
    {ticker: "QTUM", low: 0.4, high: 0.4},
    {ticker: "MTH", low: 0.4, high: 0.4},
    {ticker: "NEO", low: 0.4, high: 0.4},
    {ticker: "VEN", low: 0.4, high: 0.4},
    {ticker: "MOD", low: 0.4, high: 0.4},
    {ticker: "RDN", low: 0.4, high: 0.4},
    {ticker: "UKG", low: 0.4, high: 0.4},
    {ticker: "PPT", low: 0.4, high: 0.4},
    {ticker: "AMB", low: 0.4, high: 0.4},
    {ticker: "RPX", low: 0.4, high: 0.4},
]
